- name: Install docker
  hosts: all
  vars_prompt:
    - name: dockerhub_username
      prompt: "Enter Docker Hub username (leave blank to skip Docker Hub login)"
      private: no
      default: "tomato4"
    - name: dockerhub_token
      prompt: "Enter Docker Hub token (leave blank to skip Docker Hub login)"
      private: yes
  roles:
    - docker
