path_home: "{{ ansible_facts.env.HOME }}"
path_config: "{{ path_home }}/.config"
path_local: "{{ path_home }}/.local"
path_dotfiles: "{{ path_home }}/dotfiles"

os_macos: "{{ ansible_facts['os_family'] == 'Darwin' }}"
os_debian: "{{ ansible_facts['os_family'] == 'Debian' }}"
os_archlinux: "{{ ansible_facts['os_family'] == 'Archlinux' }}"
os_redhat: "{{ ansible_facts['os_family'] == 'RedHat' }}"
os_linux: "{{ not os_macos }}"
