path_vscode_dotfiles: "{{ path_dotfiles }}/vscode"
# VS Code's user-config dir differs per OS
path_vscode_user: "{{ (path_home + '/Library/Application Support/Code/User') if os_macos else (path_config + '/Code/User') }}"
