- name: Setup git
  hosts: all
  vars_prompt:
    - name: git_user_name
      prompt: "Enter your Git user name"
      private: no
    - name: git_user_email
      prompt: "Enter your Git user email"
      private: no
  roles:
    - git
